import * as fs from 'fs/promises';
import * as path from 'path';
import { BrainData, FileRecord } from '../types';
import { GUARD_SKILLS, buildGuardsQualitySection, renderGuardSkillFile } from './guardSkills';


export interface AgentGuideResult {
  agentsPath: string;
  agentContextPath: string;
  compactContextPath: string;
  decisionsPath: string;
  tasksPath: string;
  workflowPath: string;
  skillsIndexPath: string;
  qualityGatesPath: string;
  clineWorkflowPath: string;
  clineRulesSkillsDir: string;
  clineSkillsDir: string;
  generatedSkills: string[];
}

interface SkillDefinition {
  id: string;
  title: string;
  whenToUse: string[];
  steps: string[];
  rules: string[];
  checks: string[];
}

export class AgentGuideGenerator {
  constructor(private readonly root: string) {}

  async generate(data: BrainData): Promise<AgentGuideResult> {
    const brainDir = path.join(this.root, '.brain');
    const skillsDir = path.join(brainDir, 'skills');
    const clineWorkflowsDir = path.join(this.root, '.clinerules', 'workflows');
    const clineRulesSkillsDir = path.join(this.root, '.clinerules', 'skills');
    const clineSkillsDir = path.join(this.root, '.cline', 'skills');
    await fs.mkdir(brainDir, { recursive: true });
    await fs.mkdir(skillsDir, { recursive: true });
    await fs.mkdir(clineWorkflowsDir, { recursive: true });
    await fs.mkdir(clineRulesSkillsDir, { recursive: true });
    await fs.mkdir(clineSkillsDir, { recursive: true });

    const skills = this.detectSkills(data);
    const agentsPath = path.join(this.root, 'AGENTS.md');
    const agentContextPath = path.join(brainDir, 'agent_context.md');
    const compactContextPath = path.join(brainDir, 'compact_context.md');
    const decisionsPath = path.join(brainDir, 'decisions.md');
    const tasksPath = path.join(brainDir, 'tasks.md');
    const workflowPath = path.join(brainDir, 'workflow.md');
    const skillsIndexPath = path.join(brainDir, 'skills.md');
    const qualityGatesPath = path.join(brainDir, 'quality_gates.md');
    const clineWorkflowPath = path.join(clineWorkflowsDir, 'ini-brain-project-workflow.md');

    await Promise.all([
      this.writeAgentsFile(agentsPath, data, skills),
      fs.writeFile(agentContextPath, this.buildAgentContext(data), 'utf8'),
      fs.writeFile(compactContextPath, this.buildCompactContext(data, skills), 'utf8'),
      fs.writeFile(workflowPath, this.buildWorkflow(data, skills), 'utf8'),
      fs.writeFile(skillsIndexPath, this.buildSkillsIndex(skills), 'utf8'),
      fs.writeFile(qualityGatesPath, this.buildQualityGates(data, skills), 'utf8'),
      this.writeSkillFiles(skillsDir, skills),
      fs.writeFile(clineWorkflowPath, this.buildClineWorkflow(data, skills), 'utf8'),
      this.writeClineSkillFiles(clineRulesSkillsDir, skills),
      this.writeClineSkillFiles(clineSkillsDir, skills),
      // Always-on guard skills (clean-code/test/karpathy) in every skills dir.
      this.writeGuardSkillFiles(skillsDir),
      this.writeGuardSkillFiles(clineRulesSkillsDir),
      this.writeGuardSkillFiles(clineSkillsDir),

      this.writeIfMissing(decisionsPath, this.initialDecisions(data)),
      this.writeIfMissing(tasksPath, this.initialTasks(data))
    ]);

    return {
      agentsPath: 'AGENTS.md',
      agentContextPath: '.brain/agent_context.md',
      compactContextPath: '.brain/compact_context.md',
      decisionsPath: '.brain/decisions.md',
      tasksPath: '.brain/tasks.md',
      workflowPath: '.brain/workflow.md',
      skillsIndexPath: '.brain/skills.md',
      qualityGatesPath: '.brain/quality_gates.md',
      clineWorkflowPath: '.clinerules/workflows/ini-brain-project-workflow.md',
      clineRulesSkillsDir: '.clinerules/skills',
      clineSkillsDir: '.cline/skills',
      generatedSkills: skills.map(skill => `.brain/skills/${skill.id}.md`)
    };
  }

  async buildClineClipboardText(data: BrainData, memoryContext = ''): Promise<string> {
    const skills = this.detectSkills(data);
    return [
      '# INI Brain AI Context for Cline',
      '',
      'Use this project memory before making changes. This workspace has an AI operating system generated by INI Brain AI.',
      '',
      'Read these files first if available:',
      '- AGENTS.md',
      '- .brain/compact_context.md',
      '- .brain/workflow.md',
      '- .brain/skills.md',
      '- .brain/quality_gates.md',
      '- .brain/decisions.md',
      '- .brain/tasks.md',
      '',
      'Before editing:',
      '1. Select the relevant skill from .brain/skills.md.',
      '2. Follow .brain/workflow.md exactly.',
      '3. Apply .brain/quality_gates.md before final response.',
      '',
      'Hard rules:',
      '- Do not write secrets/API keys/tokens into files.',
      '- Do not modify .git or .brain/backups.',
      '- Prefer small diffs and preserve architecture unless explicitly asked.',
      '- Update .brain/tasks.md for notable pending work.',
      '- Update .brain/decisions.md for durable architecture decisions.',
      '',
      'Runtime memory rules:',
      '- Reuse the INI Brain Memory section below before asking the user to re-explain decisions.',
      '- If an INI Brain MCP server is available, call its context/search tools before editing and save durable discoveries after finishing.',
      '- Treat memory as guidance, but verify against current files before changing code.',
      '',
      memoryContext ? `## INI Brain Runtime Memory\n${memoryContext}` : '',
      '',
      this.buildCompactContext(data, skills)
    ].join('\n');
  }

  private async writeAgentsFile(file: string, data: BrainData, skills: SkillDefinition[]): Promise<void> {
    const generated = this.buildAgentsGeneratedSection(data, skills);
    const start = '<!-- INI:BRAIN:START -->';
    const end = '<!-- INI:BRAIN:END -->';
    const block = `${start}\n${generated}\n${end}`;

    let current = '';
    try { current = await fs.readFile(file, 'utf8'); } catch {}

    if (current.includes(start) && current.includes(end)) {
      const next = current.replace(new RegExp(`${escapeRegExp(start)}[\\s\\S]*?${escapeRegExp(end)}`), block);
      await fs.writeFile(file, next, 'utf8');
      return;
    }

    const manualHeader = current.trim()
      ? `${current.trim()}\n\n---\n\n`
      : '# AI Agent Operating Guide\n\nThis file is maintained by INI Brain AI. Add manual project rules above the generated block if needed.\n\n';

    await fs.writeFile(file, `${manualHeader}${block}\n`, 'utf8');
  }

  private buildAgentsGeneratedSection(data: BrainData, skills: SkillDefinition[]): string {
    const map = data.projectMap;
    const topFiles = this.topRecords(data, 15);
    return [
      '# INI Brain AI Generated Agent Guide',
      '',
      `Generated: ${new Date().toISOString()}`,
      `Workspace: ${map.root}`,
      `Indexed files: ${map.totalFiles}`,
      '',
      '## Project Summary',
      `Primary languages: ${this.languages(map.languages)}.`,
      `Core files: ${map.coreFiles.slice(0, 20).join(', ') || 'none detected'}.`,
      '',
      '## Agent Knowledge Files',
      '- `.brain/compact_context.md` - short token-saving project context.',
      '- `.brain/workflow.md` - required project workflow from planning to review.',
      '- `.brain/skills.md` - index of detected skills and when to use them.',
      '- `.brain/skills/*.md` - detailed playbooks for specific technologies/tasks.',
      '- `.brain/quality_gates.md` - checks to run before final delivery.',
      '- `.brain/decisions.md` - durable architecture/product decisions.',
      '- `.brain/tasks.md` - resumable task and continuity log.',
      '',
      '## Detected Skills',
      skills.map(skill => `- ${skill.title}: .brain/skills/${skill.id}.md`).join('\n') || '- None',
      '',
      '## Architecture Snapshot',
      data.architecture.trim() || 'No architecture snapshot yet. Run Scan Project first.',
      '',
      '## Important Files for Agents',
      topFiles.map(r => `- ${r.path} (${r.language}) exports: ${r.exports.slice(0, 8).join(', ') || 'none'}`).join('\n') || '- None',
      '',
      '## Required Agent Workflow',
      '1. Read this file and `.brain/compact_context.md` first.',
      '2. Select the relevant skill from `.brain/skills.md`.',
      '3. Follow `.brain/workflow.md` before editing.',
      '4. Apply `.brain/quality_gates.md` before final response.',
      '',
      '### Planner Agent',
      '- Understand the user request and inspect AGENTS.md/.brain context first.',
      '- Identify impacted files, matching skills, risks, and success criteria before editing.',
      '- Prefer a small plan with explicit verification steps.',
      '',
      '### Executor Agent',
      '- Implement minimal compatible changes following existing code style.',
      '- Keep domain boundaries and existing architecture intact.',
      '- Never write secrets/API keys into repository files.',
      '',
      '### Reviewer Agent',
      '- Check whether the requested behavior is actually satisfied.',
      '- Look for regressions, unsafe writes, missing tests/build failures, and architecture drift.',
      '- Summarize changes, verification performed, and remaining risks.',
      '',
      '## Non-Negotiable Rules',
      '- Do not modify `.git/` or `.brain/backups/`.',
      '- Do not expose API keys, tokens, or credentials.',
      '- Prefer incremental changes over rewrites.',
      '- Update `.brain/tasks.md` for notable pending work.',
      '- Update `.brain/decisions.md` for important architecture decisions.',
      '',
      '## Token-Saving Instructions for AI Agents',
      '- Start by reading this file and `.brain/compact_context.md`.',
      '- Use `.brain/skills.md` to avoid rediscovering project conventions.',
      '- Only open full source files that are directly relevant to the request.',
      '- Use `.brain/architecture.md` for project map and hotspots.',
      '- Ask for clarification when requirements are ambiguous.'
    ].join('\n');
  }

  private buildAgentContext(data: BrainData): string {
    return [
      '# Agent Context',
      '',
      'This file is optimized for AI coding agents that need durable project memory.',
      '',
      '## Project Map',
      JSON.stringify(data.projectMap, null, 2),
      '',
      '## Architecture',
      data.architecture,
      '',
      '## AI Context',
      data.aiContext
    ].join('\n');
  }

  private buildCompactContext(data: BrainData, skills: SkillDefinition[]): string {
    const map = data.projectMap;
    const records = this.topRecords(data, 25);
    return [
      '# Compact Project Context',
      '',
      `Generated: ${new Date().toISOString()}`,
      `Files: ${map.totalFiles}`,
      `Languages: ${this.languages(map.languages)}`,
      `Core files: ${map.coreFiles.slice(0, 25).join(', ') || 'none'}`,
      `Detected skills: ${skills.map(skill => skill.title).join(', ') || 'none'}`,
      '',
      '## Required Reading for Agents',
      '- AGENTS.md',
      '- .brain/workflow.md',
      '- .brain/skills.md',
      '- .brain/quality_gates.md',
      '',
      '## Key File Summaries',
      records.map(formatCompactRecord).join('\n\n') || '- None',
      '',
      '## Agent Reminder',
      'Use Planner → Executor → Reviewer. Select a relevant skill first. Prefer minimal diffs. Preserve architecture. Never write secrets.'
    ].join('\n');
  }

  private buildWorkflow(data: BrainData, skills: SkillDefinition[]): string {
    return [
      '# Project Workflow',
      '',
      `Generated: ${new Date().toISOString()}`,
      '',
      'This workflow is the default operating procedure for AI agents working in this repository.',
      '',
      '## 1. Intake',
      '- Read the user request carefully.',
      '- Read `AGENTS.md` and `.brain/compact_context.md`.',
      '- Check `.brain/tasks.md` for ongoing work.',
      '- Check `.brain/decisions.md` for durable constraints.',
      '',
      '## 2. Skill Selection',
      '- Open `.brain/skills.md`.',
      '- Select the most relevant skill file from `.brain/skills/`.',
      `- Currently detected skills: ${skills.map(skill => skill.title).join(', ') || 'none'}.`,
      '- If no skill matches, use `general-project-maintenance.md` and document the gap.',
      '',
      '## 3. Planning',
      '- Identify impacted files and modules.',
      '- Define success criteria and verification commands.',
      '- Prefer small, reversible changes.',
      '- Ask for clarification if requirements are ambiguous.',
      '',
      '## 4. Execution',
      '- Edit only relevant files.',
      '- Preserve existing architecture and naming conventions.',
      '- Never write secrets, API keys, or credentials to repository files.',
      '- Keep generated `.brain` backup files protected.',
      '',
      '## 5. Verification',
      '- Run the relevant checks from `.brain/quality_gates.md`.',
      '- For TypeScript/Node projects, prefer `npm run compile` when available.',
      '- For packaged VS Code extensions, run `npm run package` before distribution.',
      '',
      '## 6. Memory Update',
      '- Update `.brain/tasks.md` for pending or completed work.',
      '- Update `.brain/decisions.md` when architecture/product decisions are made.',
      '- Run INI Brain AI Scan/Agent Guide after major changes.',
      '',
      '## 7. Final Response',
      '- Summarize what changed.',
      '- Mention verification performed.',
      '- Mention risks or follow-up tasks.'
    ].join('\n');
  }

  private buildClineWorkflow(data: BrainData, skills: SkillDefinition[]): string {
    return [
      '# INI Brain Project Workflow',
      '',
      'Use this workflow when working in this workspace with Cline.',
      '',
      '## Trigger',
      'Use for any code, documentation, packaging, or project-memory task in this repository.',
      '',
      '## Required context',
      '- Read `AGENTS.md` first.',
      '- Read `.brain/compact_context.md` for the compact architecture summary.',
      '- Read `.brain/tasks.md` and `.brain/decisions.md` when the task may depend on prior work.',
      '',
      '## Steps',
      this.buildWorkflow(data, skills)
    ].join('\n');
  }

  private buildSkillsIndex(skills: SkillDefinition[]): string {
    return [
      '# Project Skills Index',
      '',
      'Skills are task-specific playbooks for AI agents. Before editing, choose the skill that matches the task.',
      '',
      '## Detected Skills',
      skills.map(skill => [
        `### ${skill.title}`,
        `File: .brain/skills/${skill.id}.md`,
        'Use when:',
        ...skill.whenToUse.map(item => `- ${item}`)
      ].join('\n')).join('\n\n') || '- None detected.',
      '',
      '## How Agents Should Use Skills',
      '1. Identify the type of task.',
      '2. Open the matching skill file.',
      '3. Follow its steps and rules.',
      '4. Run its checks before final response.',
      '5. If a useful skill is missing, add a note to `.brain/tasks.md`.'
    ].join('\n');
  }

  private async writeSkillFiles(skillsDir: string, skills: SkillDefinition[]): Promise<void> {
    await Promise.all(skills.map(skill => fs.writeFile(path.join(skillsDir, `${skill.id}.md`), this.formatSkill(skill), 'utf8')));
  }

  private async writeClineSkillFiles(skillsDir: string, skills: SkillDefinition[]): Promise<void> {
    await Promise.all(skills.map(skill => fs.writeFile(path.join(skillsDir, `${skill.id}.md`), this.formatClineSkill(skill), 'utf8')));
  }

  private async writeGuardSkillFiles(skillsDir: string): Promise<void> {
    await Promise.all(GUARD_SKILLS.map(skill => fs.writeFile(path.join(skillsDir, `${skill.id}.md`), renderGuardSkillFile(skill), 'utf8')));
  }


  private formatClineSkill(skill: SkillDefinition): string {
    return [
      '---',
      `name: ${skill.id}`,
      `description: ${skill.title}. Use when ${skill.whenToUse.join(' ')}`,
      '---',
      '',
      this.formatSkill(skill)
    ].join('\n');
  }

  private formatSkill(skill: SkillDefinition): string {
    return [
      `# Skill: ${skill.title}`,
      '',
      '## When to use',
      ...skill.whenToUse.map(item => `- ${item}`),
      '',
      '## Steps',
      ...skill.steps.map((item, index) => `${index + 1}. ${item}`),
      '',
      '## Rules',
      ...skill.rules.map(item => `- ${item}`),
      '',
      '## Checks',
      ...skill.checks.map(item => `- ${item}`)
    ].join('\n');
  }

  private buildQualityGates(data: BrainData, skills: SkillDefinition[]): string {
    const commands = this.recommendedCommands(data, skills);
    return [
      '# Quality Gates',
      '',
      'Use these checks before finalizing changes. Not every command applies to every task; choose the relevant ones.',
      '',
      '## Universal Gates',
      '- The requested behavior is implemented.',
      '- Changes are minimal and compatible with existing architecture.',
      '- No secrets/API keys/tokens were written to files.',
      '- `.git/` and `.brain/backups/` were not modified.',
      '- Important decisions or pending tasks were recorded when needed.',
      '',
      '## Recommended Commands',
      commands.map(command => '- `' + command + '`').join('\n') || '- No commands detected. Inspect package/build files manually.',
      '',
      '## Review Checklist',
      '- Are impacted files listed in the final response?',
      '- Were relevant skills used?',
      '- Were compile/build/test commands run when appropriate?',
      '- Are remaining risks or follow-ups documented?',
      '',
      buildGuardsQualitySection()
    ].join('\n');
  }


  private initialDecisions(data: BrainData): string {
    return [
      '# Project Decisions',
      '',
      'Record durable architecture/product decisions here so future AI agents do not need re-explanation.',
      '',
      `- ${new Date().toISOString()}: INI Brain AI initialized project memory for ${data.projectMap.totalFiles} indexed files.`
    ].join('\n');
  }

  private initialTasks(data: BrainData): string {
    return [
      '# Project Tasks and Continuity Log',
      '',
      'Use this file to keep long-running AI work resumable across sessions.',
      '',
      '## Current Status',
      `- Last memory generation: ${new Date().toISOString()}`,
      `- Indexed files: ${data.projectMap.totalFiles}`,
      '',
      '## Pending Tasks',
      '- [ ] Add project-specific tasks here.'
    ].join('\n');
  }

  private detectSkills(data: BrainData): SkillDefinition[] {
    const paths = new Set(Object.keys(data.fileIndex));
    const languages = data.projectMap.languages;
    const skills: SkillDefinition[] = [generalMaintenanceSkill()];

    if (paths.has('package.json')) skills.push(nodePackageSkill());
    if (languages.TypeScript || languages['TypeScript React']) skills.push(typescriptSkill());
    if (paths.has('src/extension.ts') || this.hasAny(paths, ['.vscodeignore']) && paths.has('package.json')) skills.push(vscodeExtensionSkill());
    if (this.hasPathPrefix(paths, 'src/ui/') || this.hasAny(paths, ['src/ui/sidebarProvider.ts', 'src/ui/settingsPanel.ts'])) skills.push(webviewSkill());
    if (this.hasAny(paths, ['vite.config.ts', 'vite.config.js']) || this.importsAny(data, ['react', 'react-dom'])) skills.push(reactFrontendSkill());
    if (this.hasAny(paths, ['composer.json', 'artisan']) || this.hasPathPrefix(paths, 'app/Http/')) skills.push(laravelSkill());
    if (this.hasAny(paths, ['pyproject.toml', 'requirements.txt']) || languages.Python) skills.push(pythonSkill());
    if (this.hasPathPrefix(paths, 'src/ai/') || this.hasPathPrefix(paths, 'src/brain/') || paths.has('AGENTS.md')) skills.push(agentMemorySkill());
    if (paths.has('package.json') && (paths.has('.vscodeignore') || paths.has('tsconfig.json'))) skills.push(packagingSkill());

    return dedupeSkills(skills);
  }

  private recommendedCommands(data: BrainData, skills: SkillDefinition[]): string[] {
    const commands = new Set<string>();
    if (data.fileIndex['package.json']) {
      commands.add('npm run compile');
      commands.add('npm run package');
    }
    for (const skill of skills) for (const check of skill.checks) {
      const match = check.match(/`([^`]+)`/);
      if (match) commands.add(match[1]);
    }
    return [...commands];
  }

  private async writeIfMissing(file: string, content: string): Promise<void> {
    try { await fs.access(file); } catch { await fs.writeFile(file, content, 'utf8'); }
  }

  private topRecords(data: BrainData, count: number): FileRecord[] {
    const core = new Set(data.projectMap.coreFiles);
    return Object.values(data.fileIndex)
      .sort((a, b) => scoreRecord(b, core) - scoreRecord(a, core))
      .slice(0, count);
  }

  private languages(languages: Record<string, number>): string {
    return Object.entries(languages).map(([k, v]) => `${k} (${v})`).join(', ') || 'none';
  }

  private hasAny(paths: Set<string>, candidates: string[]): boolean {
    return candidates.some(candidate => paths.has(candidate));
  }

  private hasPathPrefix(paths: Set<string>, prefix: string): boolean {
    return [...paths].some(file => file.startsWith(prefix));
  }

  private importsAny(data: BrainData, imports: string[]): boolean {
    const wanted = new Set(imports);
    return Object.values(data.fileIndex).some(record => record.imports.some(item => wanted.has(item)));
  }
}

function generalMaintenanceSkill(): SkillDefinition {
  return {
    id: 'general-project-maintenance',
    title: 'General Project Maintenance',
    whenToUse: ['Any task that does not match a more specific skill.', 'Repository cleanup, documentation, small fixes, or cross-cutting changes.'],
    steps: ['Read AGENTS.md and compact context.', 'Identify impacted files.', 'Make minimal changes.', 'Run relevant quality gates.', 'Update tasks/decisions if needed.'],
    rules: ['Prefer small diffs.', 'Do not rewrite architecture without explicit approval.', 'Preserve user-written content.'],
    checks: ['Review changed files manually.', 'Run the most relevant build/test command if available.']
  };
}

function nodePackageSkill(): SkillDefinition {
  return {
    id: 'node-package-management',
    title: 'Node Package Management',
    whenToUse: ['Editing package.json or package-lock.json.', 'Adding scripts, dependencies, or release metadata.'],
    steps: ['Inspect package.json scripts and dependencies.', 'Keep scripts cross-platform when possible.', 'Update lockfile when dependencies change.', 'Run compile/build after changes.'],
    rules: ['Do not add unnecessary dependencies.', 'Do not use global packages as runtime requirements.', 'Keep package metadata accurate.'],
    checks: ['Run `npm run compile` if available.', 'Run `npm run package` for extension distribution changes.']
  };
}

function typescriptSkill(): SkillDefinition {
  return {
    id: 'typescript-development',
    title: 'TypeScript Development',
    whenToUse: ['Editing .ts or .tsx files.', 'Changing exported interfaces/classes/functions.'],
    steps: ['Inspect related types and imports.', 'Keep names clear and narrow.', 'Preserve strict type safety.', 'Compile after editing.'],
    rules: ['Avoid any unless justified.', 'Keep modules cohesive.', 'Respect existing project boundaries.'],
    checks: ['Run `npm run compile`.']
  };
}

function vscodeExtensionSkill(): SkillDefinition {
  return {
    id: 'vscode-extension-development',
    title: 'VS Code Extension Development',
    whenToUse: ['Editing package.json contributes/activationEvents.', 'Registering commands or views.', 'Changing src/extension.ts.'],
    steps: ['Check package.json command/view IDs.', 'Register matching commands in src/extension.ts.', 'Keep activation events aligned.', 'Compile and package.'],
    rules: ['Keep command IDs stable unless migration is planned.', 'Do not break view provider IDs.', 'Package resources referenced by package.json.'],
    checks: ['Run `npm run compile`.', 'Run `npm run package`.']
  };
}

function webviewSkill(): SkillDefinition {
  return {
    id: 'vscode-webview-ui',
    title: 'VS Code Webview UI',
    whenToUse: ['Editing sidebarProvider.ts or settingsPanel.ts.', 'Changing HTML/CSS/JS inside VS Code webviews.'],
    steps: ['Respect Content Security Policy.', 'Use nonce scripts.', 'Use postMessage for webview-extension communication.', 'Test buttons after packaging.'],
    rules: ['Avoid inline onclick handlers.', 'Call acquireVsCodeApi only once per webview.', 'Escape user-visible dynamic content.'],
    checks: ['Run `npm run compile`.', 'Install VSIX and click affected UI controls.']
  };
}

function reactFrontendSkill(): SkillDefinition {
  return {
    id: 'react-frontend-development',
    title: 'React Frontend Development',
    whenToUse: ['Editing React components, hooks, routing, or frontend state.', 'Changing Vite/React application structure.'],
    steps: ['Identify component boundaries.', 'Keep state ownership clear.', 'Prefer reusable components.', 'Run build/type checks.'],
    rules: ['Avoid mixing data fetching, state, and UI without reason.', 'Preserve accessibility basics.', 'Keep styling consistent.'],
    checks: ['Run `npm run compile` or project build script.', 'Manually inspect affected UI paths.']
  };
}

function laravelSkill(): SkillDefinition {
  return {
    id: 'laravel-development',
    title: 'Laravel Development',
    whenToUse: ['Editing Laravel controllers, routes, models, migrations, or Blade views.'],
    steps: ['Check routes and controller flow.', 'Respect model/database boundaries.', 'Create migrations for schema changes.', 'Run relevant PHP/Laravel checks.'],
    rules: ['Do not put secrets in code.', 'Keep validation explicit.', 'Avoid changing schema without migration.'],
    checks: ['Run `php artisan test` if available.', 'Run `composer test` if configured.']
  };
}

function pythonSkill(): SkillDefinition {
  return {
    id: 'python-development',
    title: 'Python Development',
    whenToUse: ['Editing Python modules, scripts, tests, or package configuration.'],
    steps: ['Inspect pyproject/requirements.', 'Keep functions small and testable.', 'Preserve import structure.', 'Run tests/lint if available.'],
    rules: ['Avoid hidden global state.', 'Do not write credentials to files.', 'Keep error handling explicit.'],
    checks: ['Run `python -m pytest` if tests exist.', 'Run project-specific lint/type commands if configured.']
  };
}

function agentMemorySkill(): SkillDefinition {
  return {
    id: 'agent-memory-and-context',
    title: 'Agent Memory and Context Engineering',
    whenToUse: ['Editing .brain generation, AGENTS.md, compact context, skills, workflow, or decisions.', 'Improving token-saving context for AI agents.'],
    steps: ['Preserve manual content outside generated blocks.', 'Keep generated context compact but useful.', 'Add links to new memory files in AGENTS.md.', 'Verify Copy for Cline includes the right reading order.'],
    rules: ['Never overwrite user-authored decisions/tasks unless explicitly requested.', 'Keep generated markers stable.', 'Optimize for low token usage.'],
    checks: ['Run `npm run compile`.', 'Generate Agent Guide and inspect AGENTS.md/.brain files.']
  };
}

function packagingSkill(): SkillDefinition {
  return {
    id: 'release-and-vsix-packaging',
    title: 'Release and VSIX Packaging',
    whenToUse: ['Preparing a new VSIX release.', 'Changing README, package metadata, icons, or bundled resources.'],
    steps: ['Update semantic version.', 'Run compile.', 'Run package.', 'Verify generated VSIX filename and included files.'],
    rules: ['Use patch/minor/major versioning correctly.', 'Do not ship secrets or local-only files.', 'Keep README aligned with shipped behavior.'],
    checks: ['Run `npm run compile`.', 'Run `npm run package`.']
  };
}

function dedupeSkills(skills: SkillDefinition[]): SkillDefinition[] {
  const seen = new Set<string>();
  return skills.filter(skill => {
    if (seen.has(skill.id)) return false;
    seen.add(skill.id);
    return true;
  });
}

function scoreRecord(record: FileRecord, core: Set<string>): number {
  let score = 0;
  if (core.has(record.path)) score += 100;
  if (/(^|\/)(package\.json|tsconfig\.json|composer\.json|pyproject\.toml|requirements\.txt)$/i.test(record.path)) score += 50;
  score += Math.min(record.exports.length, 20);
  score += Math.min(record.imports.length, 10);
  score += record.modifiedAt / 1_000_000_000_000;
  return score;
}

function formatCompactRecord(record: FileRecord): string {
  return [
    `### ${record.path}`,
    `Language: ${record.language}`,
    `Exports: ${record.exports.slice(0, 10).join(', ') || 'none'}`,
    `Imports: ${record.imports.slice(0, 10).join(', ') || 'none'}`,
    `Summary: ${(record.summary || '').replace(/\s+/g, ' ').slice(0, 700) || 'none'}`
  ].join('\n');
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
