import { BrainData, FileRecord } from '../types';

/**
 * InsightBuilder turns the existing brain snapshot (file index + dependency
 * graph) into human/AI-readable understanding documents — without needing an
 * LLM. Adapted from the Understand-Anything builders (onboarding / explain /
 * diff-impact) but operating on INI Brain's own data model.
 */

export interface ExplainResult {
  found: boolean;
  path: string;
  markdown: string;
}

export interface ImpactResult {
  changedFiles: string[];
  mappedFiles: string[];
  unmappedFiles: string[];
  affectedFiles: string[];
  risk: 'low' | 'medium' | 'high';
  markdown: string;
}

interface Edges {
  outgoing: Map<string, Set<string>>; // file -> files it imports (resolved, in-project)
  incoming: Map<string, Set<string>>; // file -> files that import it
}

export class InsightBuilder {
  /** Build a standalone onboarding guide from the brain snapshot. */
  buildOnboarding(data: BrainData): string {
    const files = Object.values(data.fileIndex);
    const edges = buildEdges(data);
    const lines: string[] = [];

    lines.push('# Project Onboarding Guide');
    lines.push('');
    lines.push(`> Generated by INI Brain AI on ${new Date().toISOString()}`);
    lines.push('');
    lines.push('| | |');
    lines.push('|---|---|');
    lines.push(`| **Languages** | ${formatLanguages(data.projectMap.languages)} |`);
    lines.push(`| **Files** | ${data.projectMap.totalFiles} indexed |`);
    lines.push(`| **Relationships** | ${countEdges(edges.outgoing)} resolved imports |`);
    lines.push('');

    // Most connected files = best starting points.
    const hotspots = topByIncoming(files, edges, 10);
    if (hotspots.length) {
      lines.push('## Start Here (most depended-on files)');
      lines.push('');
      lines.push('These files are imported by the most modules — understanding them first unlocks the rest:');
      lines.push('');
      for (const { record, incoming } of hotspots) {
        lines.push(`- \`${record.path}\` — used by ${incoming} file(s)${record.exports.length ? `; exports: ${record.exports.slice(0, 6).join(', ')}` : ''}`);
      }
      lines.push('');
    }

    // Entry points = files that import a lot but are imported by little.
    const entryPoints = topEntryPoints(files, edges, 6);
    if (entryPoints.length) {
      lines.push('## Likely Entry Points');
      lines.push('');
      for (const record of entryPoints) {
        lines.push(`- \`${record.path}\` — wires together ${edges.outgoing.get(record.path)?.size ?? 0} module(s)`);
      }
      lines.push('');
    }

    // Complexity hotspots = biggest files / most imports.
    const complex = [...files]
      .sort((a, b) => (b.imports.length + b.size / 1000) - (a.imports.length + a.size / 1000))
      .slice(0, 8);
    if (complex.length) {
      lines.push('## Complexity Hotspots');
      lines.push('');
      lines.push('| File | Imports | Size (KB) |');
      lines.push('|------|---------|-----------|');
      for (const record of complex) {
        lines.push(`| \`${record.path}\` | ${record.imports.length} | ${(record.size / 1024).toFixed(1)} |`);
      }
      lines.push('');
    }

    lines.push('## File Map (core files)');
    lines.push('');
    lines.push('| File | Language | Exports |');
    lines.push('|------|----------|---------|');
    for (const path of data.projectMap.coreFiles.slice(0, 30)) {
      const record = data.fileIndex[path];
      if (!record) continue;
      lines.push(`| \`${path}\` | ${record.language} | ${record.exports.slice(0, 5).join(', ') || '—'} |`);
    }
    lines.push('');

    lines.push('---');
    lines.push('*Use this guide before editing. Pair it with AGENTS.md and .brain/compact_context.md.*');
    return lines.join('\n');
  }

  /** Explain a single file: what it is, what it imports, and who depends on it. */
  buildExplain(data: BrainData, relPath: string): ExplainResult {
    const record = data.fileIndex[relPath];
    if (!record) {
      return {
        found: false,
        path: relPath,
        markdown: [
          `# File Not Found in Brain: ${relPath}`,
          '',
          'This file is not in the current brain index. Try:',
          '- Running "INI Brain: Scan Project" first.',
          '- Checking the exact relative path (use forward slashes).'
        ].join('\n')
      };
    }

    const edges = buildEdges(data);
    const outgoing = [...(edges.outgoing.get(relPath) ?? new Set<string>())];
    const incoming = [...(edges.incoming.get(relPath) ?? new Set<string>())];
    const unresolved = data.dependencies.unresolved[relPath] ?? [];

    const lines: string[] = [];
    lines.push(`# Deep Dive: ${relPath}`);
    lines.push('');
    lines.push(`**Language:** ${record.language} | **Size:** ${(record.size / 1024).toFixed(1)} KB | **Exports:** ${record.exports.length} | **Imports:** ${record.imports.length}`);
    lines.push('');

    if (record.exports.length) {
      lines.push('## Exports');
      lines.push(record.exports.map(e => `- \`${e}\``).join('\n'));
      lines.push('');
    }

    lines.push('## Depends On (in-project)');
    lines.push(outgoing.length ? outgoing.map(f => `- \`${f}\``).join('\n') : '- None resolved in-project.');
    lines.push('');

    if (unresolved.length) {
      lines.push('## External / Unresolved Imports');
      lines.push(unresolved.slice(0, 30).map(f => `- ${f}`).join('\n'));
      lines.push('');
    }

    lines.push('## Used By (dependents)');
    lines.push(incoming.length ? incoming.map(f => `- \`${f}\``).join('\n') : '- No in-project file imports this one.');
    lines.push('');

    if (record.summary) {
      lines.push('## Source Preview');
      lines.push('```');
      lines.push(record.summary.slice(0, 1500));
      lines.push('```');
      lines.push('');
    }

    lines.push('## Instructions for AI');
    lines.push('Explain: (1) what this file does and why it exists, (2) how data flows through it, (3) how it interacts with its dependents/dependencies above, (4) any gotchas before editing it.');

    return { found: true, path: relPath, markdown: lines.join('\n') };
  }

  /** Analyze the ripple effect of changing a set of files. */
  buildImpact(data: BrainData, changedFiles: string[]): ImpactResult {
    const edges = buildEdges(data);
    const normalized = changedFiles.map(normalizeRel).filter(Boolean);

    const mappedFiles: string[] = [];
    const unmappedFiles: string[] = [];
    for (const file of normalized) {
      if (data.fileIndex[file]) mappedFiles.push(file);
      else unmappedFiles.push(file);
    }

    // Affected = direct dependents of changed files (1-hop incoming).
    const affected = new Set<string>();
    for (const file of mappedFiles) {
      for (const dependent of edges.incoming.get(file) ?? []) {
        if (!mappedFiles.includes(dependent)) affected.add(dependent);
      }
    }
    const affectedFiles = [...affected];

    let risk: ImpactResult['risk'] = 'low';
    if (affectedFiles.length > 10 || unmappedFiles.length > 5) risk = 'high';
    else if (affectedFiles.length > 3 || unmappedFiles.length > 0) risk = 'medium';

    const lines: string[] = [];
    lines.push(`# Change Impact Analysis`);
    lines.push('');
    lines.push(`**Changed files:** ${normalized.length} | **Affected dependents:** ${affectedFiles.length} | **Risk:** ${risk.toUpperCase()}`);
    lines.push('');

    lines.push('## Changed Files');
    lines.push(normalized.length ? normalized.map(f => `- \`${f}\`${data.fileIndex[f] ? '' : ' (not indexed)'}`).join('\n') : '- None detected.');
    lines.push('');

    lines.push('## Affected Dependents (may need review)');
    lines.push(affectedFiles.length ? affectedFiles.map(f => `- \`${f}\``).join('\n') : '- No downstream dependents detected.');
    lines.push('');

    if (unmappedFiles.length) {
      lines.push('## Unmapped / New Files');
      lines.push('These changed files are not in the brain index (run a scan to map them):');
      lines.push(unmappedFiles.map(f => `- \`${f}\``).join('\n'));
      lines.push('');
    }

    lines.push('## Risk Assessment');
    if (risk === 'high') lines.push('- **High risk**: wide blast radius and/or several unmapped files. Review dependents and re-scan.');
    else if (risk === 'medium') lines.push('- **Medium risk**: some downstream impact. Review the affected dependents above.');
    else lines.push('- **Low risk**: changes look localized with limited downstream impact.');

    return { changedFiles: normalized, mappedFiles, unmappedFiles, affectedFiles, risk, markdown: lines.join('\n') };
  }
}

function buildEdges(data: BrainData): Edges {
  const outgoing = new Map<string, Set<string>>();
  const incoming = new Map<string, Set<string>>();
  for (const [file, targets] of Object.entries(data.dependencies.edges)) {
    const set = new Set(targets);
    outgoing.set(file, set);
    for (const target of set) {
      if (!incoming.has(target)) incoming.set(target, new Set());
      incoming.get(target)!.add(file);
    }
  }
  return { outgoing, incoming };
}

function countEdges(map: Map<string, Set<string>>): number {
  let total = 0;
  for (const set of map.values()) total += set.size;
  return total;
}

function topByIncoming(files: FileRecord[], edges: Edges, limit: number): Array<{ record: FileRecord; incoming: number }> {
  return files
    .map(record => ({ record, incoming: edges.incoming.get(record.path)?.size ?? 0 }))
    .filter(item => item.incoming > 0)
    .sort((a, b) => b.incoming - a.incoming)
    .slice(0, limit);
}

function topEntryPoints(files: FileRecord[], edges: Edges, limit: number): FileRecord[] {
  return files
    .filter(record => (edges.outgoing.get(record.path)?.size ?? 0) >= 2 && (edges.incoming.get(record.path)?.size ?? 0) === 0)
    .sort((a, b) => (edges.outgoing.get(b.path)?.size ?? 0) - (edges.outgoing.get(a.path)?.size ?? 0))
    .slice(0, limit);
}

function formatLanguages(languages: Record<string, number>): string {
  return Object.entries(languages)
    .sort((a, b) => b[1] - a[1])
    .slice(0, 8)
    .map(([lang, count]) => `${lang} (${count})`)
    .join(', ') || 'unknown';
}

function normalizeRel(p: string): string {
  return p.trim().replace(/\\/g, '/').replace(/^\.\//, '');
}
